/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package kerlib.draw.settings;

import java.util.Objects;

/**
 *Универсальный набор:
 * Подпись и галочка
 * @author Kerravitarr
 */
public class BooleanPanel extends AbstractPanel<Boolean> {	
	/**
	* Создаёт панельку настройки
	* @param texter класс, который позволит получить подписи для элементов настройки
	* @param nowVal текущее значение
	* @param list слушатель, который сработает, когда значение изменится
	*/
   public BooleanPanel(TextInterface texter, boolean nowVal, java.util.function.Consumer<Boolean> list) {
		initComponents();
        initLabel(_label, texter);
		_checkBox.setToolTipText(texter.text(TextInterface.Key.TOOLTIPTEXT));
		value(!(value = !nowVal));
		
		listener = list;
        _checkBox.addChangeListener(l -> editValue());
	}
	@Override
	public void value(Boolean val) {
		if(!Objects.equals(value, val)){
			value = val;
			_checkBox.setSelected(val);
		}
	}
    
	@Override
	public void setEnabled(boolean isEnabled){
		super.setEnabled(isEnabled);
		_checkBox.setEnabled(isEnabled);
		_label.setEnabled(isEnabled);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        _checkBox = new javax.swing.JCheckBox();
        _label = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(2147483647, 40));
        setLayout(new java.awt.BorderLayout());
        add(_checkBox, java.awt.BorderLayout.CENTER);

        _label.setText("jLabel1");
        add(_label, java.awt.BorderLayout.LINE_START);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox _checkBox;
    private javax.swing.JLabel _label;
    // End of variables declaration//GEN-END:variables

}
