/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package kerlib.draw.settings;

import java.util.Arrays;

/**
 *Универсальный набор:
 * Подпись, выпадающий список, ресет
 * @author Kerravitarr
 */
public class SelectPanel<T> extends AbstractPanel<T> {
	/**
	* Создаёт панельку настройки
	* @param name название настройки, что будет у неё в заголовке
	* @param values все доступные значения
	* @param defVal значение по умолчанию
	* @param nowVal текущее значение
	* @param list слушатель, который сработает, когда значение изменится
	*/
   public SelectPanel(String name, T[] values, T defVal, T nowVal, java.util.function.Consumer<T> list) {
       this(k -> k == TextInterface.Key.LABEL ? name : null,(k,b) -> {b.setText("↻");},values, defVal,nowVal, list);
   }
	/**
	* Создаёт панельку настройки
	 * @param texter класс, который позволит получить подписи для элементов настройки
	 * @param buttoner класс, который позволит обработать кнопки подписей
	* @param values все доступные значения
	* @param defVal значение по умолчанию
	* @param nowVal текущее значение
	* @param list слушатель, который сработает, когда значение изменится
	*/
   public SelectPanel(TextInterface texter,ButtonInterface buttoner, T[] values, T defVal, T nowVal, java.util.function.Consumer<T> list) {
		initComponents();
		if (!Arrays.stream(values).anyMatch( v -> v == defVal || v != null && v.equals(defVal)))
			throw new NumberFormatException("Значение defVal("+defVal+") обязано принадлежать массиву values!("+Arrays.toString(values)+")");
		if (!Arrays.stream(values).anyMatch( v -> v == nowVal || v != null &&v.equals(nowVal)))
			throw new NumberFormatException("Значение nowVal("+nowVal+") обязано принадлежать массиву values!("+Arrays.toString(values)+")");
		if (Arrays.stream(values).filter(v -> v == null).count() > 1)
			throw new NumberFormatException("Массив values может содержать не более одного null!");
        initLabel(label, texter);
		
		this.values = new javax.swing.DefaultComboBoxModel(values);
		select.setModel(this.values);
		
        initReset(reset,buttoner, texter, defVal);

		value = nowVal == null ? Arrays.stream(values).filter( v -> v != null).findFirst().orElse(null) : null;
		SelectPanel.this.value(nowVal);
		listener = list;
		select.addActionListener((e) -> SelectPanel.this.value((T)select.getSelectedItem()));
	}
	@Override
	public void value(T val) {
		if ((val == null && val != value) || (val != null && !val.equals(value))) {
			for (int i = 0; i < values.getSize(); i++) {
				final var get = values.getElementAt(i);
				if((get == null && get == val) || (get != null && get.equals(val))){
					value = val;
					select.setSelectedIndex(i);
                    editValue();
					break;
				}
			}
		}
	}
	@Override
	public void setEnabled(boolean isEnabled){
		super.setEnabled(isEnabled);
		select.setEnabled(isEnabled);
		reset.setVisible(isEnabled);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label = new javax.swing.JLabel();
        resetAndInsert = new javax.swing.JPanel();
        reset = new javax.swing.JButton();
        select = new javax.swing.JComboBox<>();

        setMaximumSize(new java.awt.Dimension(2147483647, 40));
        setLayout(new java.awt.BorderLayout());

        label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label.setText("name");
        add(label, java.awt.BorderLayout.NORTH);

        resetAndInsert.setLayout(new java.awt.BorderLayout());

        reset.setText("reset");
        resetAndInsert.add(reset, java.awt.BorderLayout.WEST);

        add(resetAndInsert, java.awt.BorderLayout.EAST);

        select.setFocusable(false);
        select.setMaximumSize(new java.awt.Dimension(32767, 20));
        select.setMinimumSize(new java.awt.Dimension(72, 20));
        select.setPreferredSize(new java.awt.Dimension(72, 20));
        add(select, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel label;
    private javax.swing.JButton reset;
    private javax.swing.JPanel resetAndInsert;
    private javax.swing.JComboBox<T> select;
    // End of variables declaration//GEN-END:variables
	
	/**Все доступные значения */
	private javax.swing.DefaultComboBoxModel<T> values;
}
