/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package kerlib.draw.settings;

import javax.swing.JButton;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/**
 *Универсальный набор:
 * Подпись, строка для ввода, кнопка сброса
 * @author Kerravitarr
 */
public class StringPanel extends AbstractPanel<String> {
	/**
	* Создаёт панельку настройки
	 * @param texter класс, который позволит получить подписи для элементов настройки
	 * @param buttoner класс, который позволит обработать кнопки подписей
	* @param defVal значение по умолчанию
	* @param nowVal текущее значение
	* @param list слушатель, который сработает, когда значение изменится
	*/
   public StringPanel(TextInterface texter,ButtonInterface buttoner, String defVal, String nowVal,  java.util.function.Consumer<String> list) {
		initComponents();
        text.getDocument().addDocumentListener(new DocumentListener() {
            @Override public void changedUpdate(DocumentEvent e) {editValue();}
            @Override public void removeUpdate(DocumentEvent e) {editValue();}
            @Override public void insertUpdate(DocumentEvent e) {editValue();}
        });
        initLabel(label, texter);
        initReset(reset,buttoner, texter, defVal);

		value = nowVal.isEmpty() ? " " : "";
		value(nowVal);
		
		listener = list;
	}
	@Override public void value(String val) {
		if(!value.equals(val)){
			value = val;
			text.setText(val);
            editValue();
		}
	}
	@Override
	public void setEnabled(boolean isEnabled){
		super.setEnabled(isEnabled);
		text.setEnabled(isEnabled);
		reset.setVisible(isEnabled);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label = new javax.swing.JLabel();
        resetAndInsert = new javax.swing.JPanel();
        reset = new javax.swing.JButton();
        text = new javax.swing.JTextField();

        setMaximumSize(new java.awt.Dimension(2147483647, 40));
        setLayout(new java.awt.BorderLayout());

        label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label.setText("name");
        label.setAlignmentY(0.0F);
        add(label, java.awt.BorderLayout.NORTH);

        resetAndInsert.setLayout(new java.awt.BorderLayout());

        reset.setText("reset");
        resetAndInsert.add(reset, java.awt.BorderLayout.WEST);

        add(resetAndInsert, java.awt.BorderLayout.EAST);

        text.setText("jTextField1");
        add(text, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel label;
    private javax.swing.JButton reset;
    private javax.swing.JPanel resetAndInsert;
    private javax.swing.JTextField text;
    // End of variables declaration//GEN-END:variables
}
